name: Hello World
on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: gcc hello.c
      - name: Run
        run: ./hello
