name: Hello World
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: ./GHA_Test/build.sh
      - name: Run
        run: ./GHA_Test/hello
