name: Hello World
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run:  make hello
      - name: Run
        run: ./hello
