name: Hello World
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run:  make hello
      - name: Run
        run: ./hello
